version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: kanban_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: kanbancore
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: kanban_cache
    restart: unless-stopped
    # Habilita a persistência AOF para mitigar o risco mapeado na arquitetura
    command: redis-server --appendonly yes 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data: